---
title: Introduction
author: Jingchen (Monika) Hu 
institute: Vassar College
date: Data Confidentiality
output:
  beamer_presentation:
    includes:
      in_header: ../LectureStyle.tex
slide_level: 2
fontsize: 11pt

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Outline

\tableofcontents[hideallsubsections]


# Course orientation
## General info
\begin{tabular}{ p{2cm} p{8cm} }
{\underline{Instructor:}}		& Jingchen (Monika) Hu - {jihu@vassar.edu} \\
				& RH 403  \\
				& \\	
%{\underline{Stats Intern:}}		& Baian Liu (senior) -  \webLink{mailto:baliu@vassar.edu}{{baliu@vassar.edu}} \\
%                & \\
{\underline{Lecture:}}		&  Tuesdays 3:10-5:10pm \\
                & RH 101 \\
				& \\
{\underline{Lab:}}			& Some lectures will be used as labs.\\
                & \\
{\underline{Office hours:}} & Wednesday 10:00am-12:00pm \& Thursday 11:30am-12:30pm, or by appointment. \\ 
                & \\
%{\underline{TAs:}} & Dahlia Forte, Lucas Krishan, and Henrik Olsson \\ 
                & \\
\end{tabular}

## Required materials

\begin{tabular}{ p{2cm} p{8cm} }
{\underline{Prerequisite:}} &  MATH 347 Bayesian Statistics, and interests in data confidentiality\\
                & \\

{\underline{Readings:}} 	&  A collection of selected journal articles and manuscripts \\
			& \\	
{\underline{Software:}}    & We will use the software R/RStudio for labs and project. Download R from \href{http://www.r-project.org/}{\textit{http://www.r-project.org/}} and RStudio, from \href{https://www.rstudio.com/}{\textit{https://www.rstudio.com/}} \\
            & \\

{\underline{Webpage:}} & The course GitHub page \href{https://github.com/monika76five/Data-Confidentiality}{\textit{https://github.com/monika76five/Data-Confidentiality}}. Tentative schedule, to-do lists, datasets, R scripts...\\
\end{tabular}

## Course topics

- \underline{Disclosure risks} in microdata

- \underline{Protection methods} for microdata
    - Bayesian data synthesis
        - for continuous variables
        - for binary variables
        - for categorical variables
    

- \underline{Evaluation} of protection methods
    - data utility
    - disclosure risks

- Other protection methods
    - differential privacy
    - differentially private data synthesis


## Course components

- The three parts of material: \underline{disclosure risks, protection, evaluation}

\pause

- Each part is a combination of a selection of the following: readings, lectures, labs, homework, discussions (in-class and online), and project

\pause

- The course project (individual or in pair; cross-campus collaboration is highly encouraged!) is a final product, using Bayesian data synthesis to provide privacy protection

## Course project

- Find a dataset and demonstrate disclosure risks

- Design and implement protection methods

- Evaluate protection methods
  
- Write a paper and present the results
    
\vspace{5mm}

\pause 

Questions? Ideas to discuss and share?



