---
title: "ARCalculation"
author: "Sarah Boese"
date: "4/6/2020"
output: pdf_document
---

```{r, message = FALSE}
library(ProbBayes)
library(dplyr)
library(ggplot2)
require(gridExtra)
library(reshape)
library(runjags)
library(coda)
library(tidyverse)
library(fastDummies)
crcblue <- "#2905a1"
```

```{r}
CEdata<-read.csv("CEsample2.csv")
names(CEdata)<-c("UrbanRural", "Income", "Race", "Expenditure")
CESample <- read.csv("CEsample2.csv")
```

```{r}
CEdata$LogIncome <- log(CEdata$Income) 
CEdata$LogExpenditure <- log(CEdata$Expenditure)
```



```{r}
CESample <- CESample %>%
  mutate(LogTotalIncome = log(TotalIncomeLastYear))
CESample <- CESample %>%
  mutate(LogTotalExp = log(TotalExpLastQ))
```


```{r message = FALSE, echo=FALSE}
CESample$Log_TotalExpSTD <- scale(CESample$LogTotalExp)
CESample$Log_TotalIncomeSTD <- scale(CESample$LogTotalIncome)
## create indictor variable for Rural
CESample$Rural = fastDummies::dummy_cols(CESample$UrbanRural)[,names(fastDummies::dummy_cols(CESample$UrbanRural))
 == ".data_2"]
```

```{r message = FALSE, echo=FALSE}
## create indicator variables for Black (2), Native American (3), 
## Asian (4), Pacific Islander (5), and Multi-race (6)
CESample$Race_Black = fastDummies::dummy_cols(CESample$Race)[,names(fastDummies::dummy_cols(CESample$Race)) == ".data_2"]
CESample$Race_NA = fastDummies::dummy_cols(CESample$Race)[,names(fastDummies::dummy_cols(CESample$Race)) == ".data_3"]
CESample$Race_Asian = fastDummies::dummy_cols(CESample$Race)[,names(fastDummies::dummy_cols(CESample$Race)) == ".data_4"]
CESample$Race_PI = fastDummies::dummy_cols(CESample$Race)[,names(fastDummies::dummy_cols(CESample$Race)) == ".data_5"]
CESample$Race_M = fastDummies::dummy_cols(CESample$Race)[,names(fastDummies::dummy_cols(CESample$Race)) == ".data_6"]
```

```{r message = FALSE, echo=FALSE}
modelString <-"
model {
## sampling
for (i in 1:N){
y[i] ~ dnorm(beta0 + beta1*x_exp[i] + beta2*x_rural[i] +
beta3*x_race_B[i] + beta4*x_race_N[i] +
beta5*x_race_A[i] + beta6*x_race_P[i] +
beta7*x_race_M[i], invsigma2)
}
## priors
beta0 ~ dnorm(mu0, g0)
beta1 ~ dnorm(mu1, g1)
beta2 ~ dnorm(mu2, g2)
beta3 ~ dnorm(mu3, g3)
beta4 ~ dnorm(mu4, g4)
beta5 ~ dnorm(mu5, g5)
beta6 ~ dnorm(mu6, g6)
beta7 ~ dnorm(mu7, g7)
invsigma2 ~ dgamma(a, b)
sigma <- sqrt(pow(invsigma2, -1))
}
"
```

- Pass the data and hyperparameter values to JAGS:

```{r message = FALSE, ehco=FALSE}
y_income = as.vector(CESample$LogTotalIncome)
x_exp = as.vector(CESample$LogTotalExp)
x_rural = as.vector(CESample$Rural)
x_race_B = as.vector(CESample$Race_Black)
x_race_N = as.vector(CESample$Race_NA)
x_race_A = as.vector(CESample$Race_Asian)
x_race_P = as.vector(CESample$Race_PI)
x_race_M = as.vector(CESample$Race_M)
N = length(y_income)  # Compute the number of observations
```

- Pass the data and hyperparameter values to JAGS:

```{r message = FALSE, echo=FALSE}
the_data <- list("y" = y_income, "x_exp" = x_exp,
                 "x_rural" = x_rural, "x_race_B" = x_race_B,
                 "x_race_N" = x_race_N, "x_race_A" = x_race_A,
                 "x_race_P" = x_race_P, "x_race_M" = x_race_M,
                 "N" = N,
                 "mu0" = 0, "g0" = 0.0001, "mu1" = 0, "g1" = 0.0001,
                 "mu2" = 0, "g2" = 1, "mu3" = 0, "g3" = 1,
                 "mu4" = 0, "g4" = 1, "mu5" = 0, "g5" = 1,
                 "mu6" = 0, "g6" = 1, "mu7" = 0, "g7" = 1,
                 "a" = 1, "b" = 1)
```

- Pass the data and hyperparameter values to JAGS:

```{r message = FALSE, size = "footnotesize", echo=FALSE}
initsfunction <- function(chain){
  .RNG.seed <- c(1,2)[chain]
  .RNG.name <- c("base::Super-Duper",
                 "base::Wichmann-Hill")[chain]
  return(list(.RNG.seed=.RNG.seed,
              .RNG.name=.RNG.name))
}
```

- Run the JAGS code for this model:

```{r message = FALSE, echo=FALSE}
synthesize_log_income<-function(index){
posterior_MLR <- run.jags(modelString,
                      n.chains = 1,
                      data = the_data,
                      monitor = c("beta0", "beta1", "beta2",
                                  "beta3", "beta4", "beta5",
                                  "beta6", "beta7", "sigma"),
                      adapt = 1000,
                      burnin = 5000,
                      sample = 5000,
                      thin = 10,
                      inits = initsfunction)

post_MLR <- as.mcmc(posterior_MLR)
n <- nrow(CESample)
params <- data.frame(y_income, x_exp, x_rural, x_race_B, x_race_N, x_race_A, x_race_P, x_race_M)
synthetic_one <- synthesize(params, index, n, post_MLR)
names(synthetic_one) <- c("LogIncome")
return(list(synthetic_one, post_MLR))
}
```

```{r, echo=FALSE}
synthesize <- function(X, index, n, post_MLR){
  mean_Y <- post_MLR[index, "beta0"] + X$x_exp * post_MLR[index, "beta1"] + X$x_rural * post_MLR[index, "beta2"] +   X$x_race_B * post_MLR[index, "beta3"] +  X$x_race_N * post_MLR[index, "beta4"] +  X$x_race_A * post_MLR[index,   "beta5"] +  X$x_race_P * post_MLR[index, "beta6"] +  X$x_race_M * post_MLR[index, "beta7"]
  synthetic_Y <- rnorm(n,mean_Y, post_MLR[index,"sigma"])
  return(data.frame(synthetic_Y))
}
```



```{r}
n<-nrow(CEdata)
synthetic_list<-synthesize_log_income(1)
synthetic_one<- synthetic_list[[1]]
post<-synthetic_list[[2]]
```

```{r}
CEdata_org <- CEdata[, 1:4]
CEdata_syn <- as.data.frame(cbind(CEdata_org[, "UrbanRural"],
                            exp(synthetic_one[, "LogIncome"]),
                            cbind(CEdata_org [, c("Race","Expenditure")]))) 
names(CEdata_syn) <- c("UrbanRural", "Income", "Race", "Expenditure")
```

```{r}
CEdata_org$LogIncome <- round(log(CEdata_org$Income), digits = 1)
CEdata_org$LogExpenditure <- round(log(CEdata_org$Expenditure), digits = 1)
CEdata_syn$LogIncome <- round(log(CEdata_syn$Income), digits = 1)
CEdata_syn$LogExpenditure <- round(log(CEdata_syn$Expenditure), digits = 1)
```

```{r}
compute_logsumexp <- function(log_vector){ 
  log_vector_max <- max(log_vector)
  exp_vector <- exp(log_vector - log_vector_max) 
  sum_exp <- sum(exp_vector)
  log_sum_exp <- log(sum_exp) + log_vector_max
  return(log_sum_exp) 
}
```

```{r}
calc_prob_rank<-function(i, H, post){
  y_i <- CEdata_org$LogIncome[i]
  y_i_guesses <- seq((y_i - 2.5), (y_i + 2.5), 0.5) 
  X_i <- CEdata_syn$LogExpenditure[i]
  G <- length(y_i_guesses)
  beta0_draws <- post[1:H, "beta0"] 
  beta1_draws <- post[1:H, "beta1"] 
  sigma_draws <- post[1:H, "sigma"]
  
  CU_i_logZ_all <- rep(NA, G) 
  for (g in 1:G){
    q_sum_H <- sum((dnorm(y_i_guesses[g],
    mean = (beta0_draws + beta1_draws * X_i),
    sd = sigma_draws)) /(dnorm(y_i, mean = (beta0_draws + beta1_draws * X_i), sd = sigma_draws))) 
    log_pq_h_all <- rep(NA, H)
    for (h in 1:H){
      log_p_h <- sum(log(dnorm(CEdata_syn$LogIncome, mean = (beta0_draws[h] + beta1_draws[h] *
                                                               CEdata_syn$LogExpenditure), sd = sigma_draws[h])))
      log_q_h <- log(((dnorm(y_i_guesses[g], mean = (beta0_draws[h] + beta1_draws[h] * X_i), sd = sigma_draws[h])) /
                    (dnorm(y_i, mean = (beta0_draws[h] + beta1_draws[h] * X_i),
                             sd = sigma_draws[h]))) / q_sum_H) 
      log_pq_h_all[h] <- log_p_h + log_q_h
    }
    CU_i_logZ_all[g] <- compute_logsumexp(log_pq_h_all) 
  }
  prob <- exp(CU_i_logZ_all - max(CU_i_logZ_all)) / sum(exp(CU_i_logZ_all - max(CU_i_logZ_all)))
  outcome <- as.data.frame(cbind(y_i_guesses, prob)) 
  names(outcome) <- c("guess", "probability") 
  outcome[order(outcome$probability, decreasing = TRUE), ]
  rank<-which(outcome[,1]==y_i)
  rank_df<-slice(outcome, rank)
  probability<-as.numeric(rank_df$probability)
  out<-data.frame(rank, probability)
  names(out)<-c("rank","probability")
  return(out)
}
```

```{r}
prob_rank_df<-calc_prob_rank(1, 50,post)
for(i in 2:n){
  prob_rank_df_i<-calc_prob_rank(i,50,post)
  prob_rank_df<-bind_rows(prob_rank_df, prob_rank_df_i)
}
```

