---
header-includes:
- \usepackage{color}
- \usepackage[dvipsnames]{xcolor}
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---
----
 Spring 2020: MATH 301-56 Data Confidentiality
---
---
----
 Fall 2019: MATH 347 Bayesian Statistics
---
```{r}
library(ggplot2)
library(runjags)
library(readxl)
library(coda)
```

```{r}
CEdata <- read_excel("C:/Users/Ted Xie/Downloads/CEdata.xlsx")
```

```{r}
CEdata$LogIncome <- log(CEdata$Income)
CEdata$LogExpenditure <- log(CEdata$Expenditure)

summary(CEdata)
ggplot(CEdata, aes(x = LogExpenditure, y = LogIncome)) + geom_point(size = 1) + labs(title = "Scatter plot of Log Income vs Log Expenditure") + theme_bw(base_size = 6, base_family = "")
```

```{r}
modelString <-" 
model { 
## sampling 
for (i in 1:N){
y[i] ~ dnorm(beta0 + beta1*x[i] +beta2*z[i] + beta3*xx[i], invsigma2) 
}

## priors 
beta0 ~ dnorm(mu0, g0) 
beta1 ~ dnorm(mu1, g1)
beta2 ~ dbeta(mu2, g2)
beta3 ~ dbeta(1, 1)
invsigma2 ~ dgamma(a, b) 
sigma <- sqrt(pow(invsigma2, -1)) 
} 
"

xx <- as.vector(CEdata$Race)
z <- as.vector(CEdata$UrbanRural)
y <- as.vector(CEdata$LogIncome) 
x <- as.vector(CEdata$LogExpenditure)
N <- length(y) 
the_data <- list("y" = y, "x" = x, "z" = z, "xx" = xx, "N" = N, "mu0" = 0, "g0" = 0.0001, "mu1" = 0, "g1" = 0.0001, "a" = 1, "b" = 1, "mu2" = 1, "g2"= 10)
initsfunction <- function(chain){ 
  .RNG.seed <- c(1,2)[chain] 
  .RNG.name <- c("base::Super-Duper", "base::Wichmann-Hill")[chain] 
  return(list(.RNG.seed=.RNG.seed, .RNG.name=.RNG.name)) }

posterior <- run.jags(modelString, n.chains = 1, data = the_data, monitor = c("beta0", "beta1", "beta2", "beta3", "sigma"), adapt = 1000, burnin = 5000, sample = 5000, thin = 50, inits = initsfunction)

```

```{r}
post <- as.mcmc(posterior)
synthesize <- function(X, Z, XX, index, n){ 
  mean_Y <- post[index, "beta0"] + X * post[index, "beta1"] + Z * post[index, "beta2"] + XX * post[index, "beta3"]
  synthetic_Y <- rnorm(n, mean_Y, post[index, "sigma"]) 
  data.frame(X, synthetic_Y) 
  }

n <- dim(CEdata)[1] 
synthetic_one <- synthesize(CEdata$LogExpenditure, CEdata$UrbanRural, CEdata$Race, 1, n) 
names(synthetic_one) <- c("logExpenditure", "logIncome_syn")
```

```{r}
summary(synthetic_one)
ggplot(synthetic_one, aes(x = logExpenditure, y = logIncome_syn)) + geom_point(size = 1) + labs(title = "Scatter plot of Synthesized Log Income vs Log Expenditure") + theme_bw(base_size = 6, base_family = "")
```
Propensity Score
```{r}
df1 <- data.frame(Income = synthetic_one$logIncome_syn, expend = CEdata$LogExpenditure, syn = 1)
df2 <- data.frame(Income = CEdata$LogIncome, expend = CEdata$LogExpenditure, syn = 0)
merged <- rbind(df1, df2)
logistic <- glm(syn ~ Income + expend, data = merged, family = "binomial")
#summary(logistic)
#intercept <- -0.011590
#slope1 <- 0.002742
#slope2 <- 0.001988
#income <- merged[,1]
#expenditure <- merged[,2]

N <- length(merged)
c <- 1/2
#d <- intercept + slope1 * income + slope2 * expenditure
#p_i <- d/(1 + d)
#diff <- (p_i - c)^2
pred <- predict(logistic, data = merged)
probs <- exp(pred)/(1 + exp(pred))
U_p <- sum((probs - c)^2) / N
U_p
```

Cluster Analysis Measure
```{r}
clusters <- hclust(dist(merged[,1:2]), method = 'average')
G <- 5
clusterCut <- cutree(clusters, G)
cluster_S <- as.data.frame(cbind(clusterCut,merged$syn))
names(cluster_S) <- c("cluster", "S")
n_gS <- table(cluster_S)[, 1]
n_g <- rowSums(table(cluster_S))
w_g <- n_g / N
U_c <- (1/G) * sum(w_g * (n_gS/n_g - c)^2)
U_c
```

Emperical CDF Measures
```{r}
S_x <- ecdf(CEdata$LogIncome)
S_y <- ecdf(synthetic_one$logIncome_syn)
#Sdiff <- c()
#for(i in 1:length(CEdata$LogIncome)){
#  Sdiff <- c(Sdiff, (CEdata$LogIncome[i] - synthetic_one$logIncome_syn[i])^2)
#}
percentile_orig <- S_x(merged[,"Income"])
percentile_syn <- S_y(merged[,"Income"])

ecdf_diff <- percentile_orig - percentile_syn

U_m <- max(abs(ecdf_diff))
U_s <- mean((ecdf_diff)^2)
U_m
U_s
```

```{r}
m <- 20
synthetic_m <- vector("list", m)

for (j in 1:m){
  synthetic_j <- synthesize(CEdata$LogExpenditure, CEdata$UrbanRural, CEdata$Race, 1, n)
  names(synthetic_j) <- c("logExpenditure", "logIncome_syn")
  synthetic_m[[j]] <- synthetic_j
}
```

```{r}
syn_mean <- vector("list", m)
for (j in 1:m){
  syn_mean[[j]] <- mean(synthetic_m[[j]]$logIncome_syn)
}
syn_mean <- unlist(syn_mean)

q_m_bar <- mean(syn_mean)
b_m <- sum((syn_mean - q_m_bar)^2/(m - 1))
u_m_bar <- var(syn_mean)

T_p <- b_m/m + u_m_bar

q_m_bar
b_m
u_m_bar
T_p
```
```{r}
L_o <- quantile(CEdata$LogExpenditure, .05)
U_o <- quantile(CEdata$LogExpenditure, .9)
L_s <- quantile(synthetic_one$logIncome_syn, .05)
U_s <- quantile(synthetic_one$logIncome_syn, .9)
L_i <- max(L_s, L_o)
U_i <- min(U_s, U_o)

I <- (U_i - L_i)/(2 * (U_o - L_o)) + (U_i - L_i)/(2 * (U_s - L_s))

I
```
