---
title: "April 7 assignment"
author: "Henrik Olsson"
date: "April 7, 2020"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
subtitle: MATH 301 Data Confidentiality
---
```{r include=FALSE}
library(readr)
library(LearnBayes)
library(plyr)
library(dplyr)
library(ggplot2)
library(runjags)
library(coda)
library(imputeTS)
library(fastDummies)
library(tinytex)
```

## CE sample synthesis
```{r message=FALSE, size = "footnotesize"}
CEdata <- read.csv(file = "CEdata.csv")
CEdata$LogIncome <- log(CEdata$Income)
CEdata$LogExpenditure <- log(CEdata$Expenditure)
```

```{r message = FALSE, echo = FALSE, warning = FALSE, results = 'hide'}
modelString <-"
model {
## sampling
for (i in 1:N){
y[i] ~ dnorm(beta0 + beta1*x[i], invsigma2)
}
## priors
beta0 ~ dnorm(mu0, g0)
beta1 ~ dnorm(mu1, g1)
invsigma2 ~ dgamma(a, b)
sigma <- sqrt(pow(invsigma2, -1))
}
"
y <- as.vector(CEdata$LogIncome)
x <- as.vector(CEdata$LogExpenditure)
N <- length(y)
the_data <- list("y" = y, "x" = x, "N" = N,
                 "mu0" = 0, "g0" = 0.0001,
                 "mu1" = 0, "g1" = 0.0001,
                 "a" = 1, "b" = 1)
initsfunction <- function(chain){
  .RNG.seed <- c(1,2)[chain]
  .RNG.name <- c("base::Super-Duper",
                 "base::Wichmann-Hill")[chain]
  return(list(.RNG.seed=.RNG.seed,
              .RNG.name=.RNG.name))
}
posterior <- run.jags(modelString,
                      n.chains = 1,
                      data = the_data,
                      monitor = c("beta0", "beta1", "sigma"),
                      adapt = 1000,
                      burnin = 5000,
                      sample = 5000,
                      thin = 50,
                      inits = initsfunction)
post <- as.mcmc(posterior)
synthesize_loginc <- function(X, index, n, seed){
  set.seed(seed)
  mean_Y <- post[index, "beta0"] +  X * post[index, "beta1"]
  synthetic_Y <- rnorm(n, mean_Y, post[index, "sigma"])
  data.frame(X, synthetic_Y)
}
```

```{r message=FALSE, size = "footnotesize"}
n <- dim(CEdata)[1]
synthetic_one <- synthesize_loginc(CEdata$LogExpenditure, 
                                   1, n, seed = 123)
names(synthetic_one) <- c("LogExpenditure", "LogIncome")
CEdata_org <- CEdata[, 1:4]
CEdata_syn <- as.data.frame(cbind(CEdata_org[, "UrbanRural"], 
                                  exp(synthetic_one
                                      [, "LogIncome"]),
                                  cbind(CEdata_org
                                        [, c("Race", 
                                             "Expenditure")])))
names(CEdata_syn) <- c("UrbanRural", "Income", 
                       "Race", "Expenditure")
```

```{r}
CEdata_org$LogIncome <- round(log(CEdata_org$Income), 
                              digits = 1)
CEdata_org$LogExpenditure <- round(log(CEdata_org$Expenditure), 
                                   digits = 1)
CEdata_syn$LogIncome <- round(log(CEdata_syn$Income), 
                              digits = 1)
CEdata_syn$LogExpenditure <- round(log(CEdata_syn$Expenditure), 
                                   digits = 1)

i <- 8
y_i <- CEdata_org$LogIncome[i]
y_i_guesses <- seq((y_i - 2.5), (y_i + 2.5), 0.5)
X_i <- CEdata_syn$LogExpenditure[i]
G <- length(y_i_guesses)

compute_logsumexp <- function(log_vector){
  log_vector_max <- max(log_vector)
  exp_vector <- exp(log_vector - log_vector_max)
  sum_exp <- sum(exp_vector)
  log_sum_exp <- log(sum_exp) + log_vector_max
  return(log_sum_exp)
}

H <- 50
beta0_draws <- post[1:H, "beta0"]
beta1_draws <- post[1:H, "beta1"]
sigma_draws <- post[1:H, "sigma"]

CU_i_logZ_all <- rep(NA, G)
for (g in 1:G){
  q_sum_H <- sum((dnorm(y_i_guesses[g], 
                        mean = (beta0_draws + beta1_draws * X_i), 
                        sd = sigma_draws)) / 
            (dnorm(y_i, mean = (beta0_draws + beta1_draws * X_i), 
                   sd = sigma_draws)))
  log_pq_h_all <- rep(NA, H)
  for (h in 1:H){
    log_p_h <- sum(log(dnorm(CEdata_syn$LogIncome, 
                             mean = (beta0_draws[h] + beta1_draws[h] * 
                                       CEdata_syn$LogExpenditure), 
                             sd = sigma_draws[h])))
  
    log_q_h <- log(((dnorm(y_i_guesses[g], 
                           mean = (beta0_draws[h] + beta1_draws[h] * X_i), 
                           sd = sigma_draws[h])) / 
            (dnorm(y_i, mean = (beta0_draws[h] + beta1_draws[h] * X_i), 
                   sd = sigma_draws[h]))) / q_sum_H)
    log_pq_h_all[h] <- log_p_h + log_q_h
  }
  CU_i_logZ_all[g] <- compute_logsumexp(log_pq_h_all)
}

prob <- exp(CU_i_logZ_all - max(CU_i_logZ_all)) / 
  sum(exp(CU_i_logZ_all - max(CU_i_logZ_all)))
outcome <- as.data.frame(cbind(y_i_guesses, prob))
names(outcome) <- c("guess", "probability")
outcome[order(outcome$probability, decreasing = TRUE), ]
```


```{r}
LogIncome_ori <- round(CEdata$LogIncome, digits = 1)
LogIncome_syn <- round(synthetic_one$logIncome_syn, digits = 1)
LogExpenditure_ori <- round(CEdata$LogExpenditure, digits = 1)
LogExpenditure_syn <- round(synthetic_one$logExpenditure, digits = 1)
compute_logsumexp <- function(log_vector){
  log_vector_max <- max(log_vector)
  exp_vector <- exp(log_vector - log_vector_max)
  sum_exp <- sum(exp_vector)
  log_sum_exp <- log(sum_exp) + log_vector_max
  return(log_sum_exp)
}
CUProb <- function(n){
  List <- list()
  
  G <- 11
  H <- 50
  beta0_draws <- post[1:H, "beta0"]
  beta1_draws <- post[1:H, "beta1"]
  sigma_draws <- post[1:H, "sigma"]
  for(i in 1:n){
    y_i <- LogIncome_ori[i]
    y_i_guesses <- seq((y_i - 2.5), (y_i + 2.5), 0.5)
    X_i <- LogExpenditure_syn[i]
    
    CU_i_logZ_all <- rep(NA, G)
    for (g in 1:G){
      q_sum_H <- sum((dnorm(y_i_guesses[g], mean = (beta0_draws + beta1_draws * X_i), sd =
                              sigma_draws)) /(dnorm(y_i, mean = (beta0_draws + beta1_draws *
                                                                   X_i), sd = sigma_draws)))
      log_pq_h_all <- rep(NA, H)
      for (h in 1:H){
        log_p_h <- sum(log(dnorm(LogIncome_syn, mean = (beta0_draws[h] + beta1_draws[h] *
                       LogExpenditure_syn), sd = sigma_draws[h])))
        log_q_h <- log(((dnorm(y_i_guesses[g],
                         mean = (beta0_draws[h] + beta1_draws[h] * X_i), sd = sigma_draws[h]))                          / (dnorm(y_i, mean = (beta0_draws[h] + beta1_draws[h] * X_i), sd =
                        sigma_draws[h]))) / q_sum_H)
        log_pq_h_all[h] <- log_p_h + log_q_h
      }
      CU_i_logZ_all[g] <- compute_logsumexp(log_pq_h_all)
    }
    
    prob <- exp(CU_i_logZ_all - max(CU_i_logZ_all)) / sum(exp(CU_i_logZ_all -
                                                                max(CU_i_logZ_all)))
    outcome <- as.data.frame(cbind(y_i_guesses, prob))
    names(outcome) <- c("guess", "probability")
    
    List[[i]] <- outcome[order(outcome$probability, decreasing = TRUE), ]
  }
  return (List)
}

prob <- exp(CU_i_logZ_all - max(CU_i_logZ_all)) / 
  sum(exp(CU_i_logZ_all - max(CU_i_logZ_all)))
outcome <- as.data.frame(cbind(y_i_guesses, prob))
names(outcome) <- c("guess", "probability")
outcome[order(outcome$probability, decreasing = TRUE), ]
```

```{r}
Result_list <- CUProb(n)
```

```{r}
Result_list[[7]]
```
